[package]
name = "push_doc"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonic = "0.2.12"
spinners = "4.1.1"
tokio = { version = "1.38.0", features = ["full"] }
rand = "*"
tokio-rustls = "*"
#sha256 = "*"
rustls-pemfile = "*"
webpki-roots = "*"
