{
id=1kVGyd1WW_qqcjFqf56YkET2Y_77Bct-FCZP0qCXl0yo
client_secrets=$[client_secret_1014602435348-6317hvuq1n0stf3p9hqlqnplls8cb336.apps.googleusercontent.com.json]$
insertText=(INSERT_NO_0,END)
insertText=(INSERT_NO_1,END)
replaceAllText=(hello,idkhw)
}

{
id=1kVGyd1WW_qqcjFqf56YkET2Y_77Bct-FCZP0qCXl0yo
client_secrets=$[client_secret_1014602435348-6317hvuq1n0stf3p9hqlqnplls8cb336.apps.googleusercontent.com.json]$
insertText=(INSERT_NO_2,END)
insertText=(INSERT_NO_3,END)
replaceAllText=(kaching,bing)
}
